# Generated by Django 3.0.7 on 2020-06-24 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duchess', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='duchess.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='victories',
            field=models.IntegerField(null=True),
        ),
    ]
